//Criando usuário
POST http://localhost:3000/criar_usuarios
Content-Type: application/json

{
    "title": "Conta 01",
    "description": "Usuário admin",
    "username": "admin",
    "password": "123456"
}

###
//Mostrando o usuário(s)
GET http://localhost:3000/criar_usuarios    

###
//Atualizando as informações do usuário apartir de seu ID
PUT  http://localhost:3000/criar_usuarios/
Content-Type: application/json

{
    "title": "Conta 01",
    "description": "Usuário admin",
    "username": "admin",
    "password": "123456"
}

###
//Acessando o usuário
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
//Apagando o usuário a partir de seu ID
DELETE http://localhost:3000/criar_usuarios/1306e6ff-ec9e-4d58-9c92-5ab6b8c02b3b

